# Site settings
title:       'Jespers Resourcer'
email:
description: 'Private Site'
url:         'https://jquorning.github.io'
baseurl:
twitter_username:
github_username:  jquorning

# Build settings
markdown: kramdown
permalink: pretty
