# Site settings
title:       'Ada on GitHub'
email:
description: 'Community Site'
url:         'https://jquorning.github.io'
baseurl:     '/ada'
twitter_username:
github_username:  jquorning

# Build settings
markdown: kramdown
permalink: pretty
